# Generated by Django 4.1.7 on 2023-05-09 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('detail', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(choices=[(0, 'TRANSFER_MONEY'), (1, 'RECIEVE_MONEY')], max_length=32)),
                ('payment_method', models.CharField(default='CASH', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('available_amount', models.FloatField(default=0)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='transaction_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('available_amount__gte', 0)), name='available_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('base_user',), name='unique_wallet_person'),
        ),
    ]
