# Generated by Django 4.1.7 on 2023-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[(0, 'BANKING'), (1, 'CASH')], max_length=32),
        ),
    ]
