# Generated by Django 4.1.7 on 2023-05-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_diagnosticbilldetail_distance_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diagnosticbilldetail',
            name='total_fee_gte_0',
        ),
        migrations.RemoveField(
            model_name='diagnosticbilldetail',
            name='total_fee',
        ),
        migrations.AlterField(
            model_name='diagnosticbilldetail',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='Transaction.diagnosticbill'),
        ),
    ]
