# Generated by Django 4.1.7 on 2023-05-13 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transaction', '0006_remove_diagnosticbilldetail_total_fee_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='base_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
