# Generated by Django 4.1.7 on 2023-05-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0006_alter_diagnosticbill_diagnostic_form'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diagnosticbilldetail',
            name='total_fee_gte_0',
        ),
        migrations.RemoveField(
            model_name='diagnosticbilldetail',
            name='total_fee',
        ),
    ]
