# Generated by Django 4.1.7 on 2023-04-22 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('symptom', models.TextField()),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('condition', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MedicalRecord',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('note', models.TextField(null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalRecordManagement.medicalrecord')),
            ],
            options={
                'db_table': 'Prescription',
            },
        ),
    ]
