# Generated by Django 4.1.7 on 2023-04-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecordManagement', '0003_remove_prescription_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalRecordManagement.prescription'),
        ),
    ]
