# Generated by Django 4.1.7 on 2023-04-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecordManagement', '0004_medicalrecord_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalRecordManagement.prescription'),
        ),
    ]
