# Generated by Django 4.1.7 on 2023-04-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecordManagement', '0005_alter_medicalrecord_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='prescription',
        ),
    ]
