# Generated by Django 4.1.7 on 2023-04-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecordManagement', '0006_remove_medicalrecord_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalRecordManagement.medicalrecord'),
        ),
    ]
