# Generated by Django 4.1.7 on 2023-04-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecordManagement', '0008_medicalrecord_doctor_medicalrecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='MedicalRecordManagement.medicalrecord'),
        ),
    ]
