# Generated by Django 4.1.7 on 2023-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecordManagement', '0009_alter_prescription_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
