# Generated by Django 4.1.7 on 2023-05-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecordManagement', '0010_remove_prescription_id_prescription_prescription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
