version: '3'
services:
  db:
    image: mysql:8.0.32-debian
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 33320:3306
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD : capstone2
       MYSQL_PASSWORD : capstone2
       MYSQL_USER  : capstone2
       MYSQL_DATABASE : capstone2

  backend:
    image: python:3.9
    container_name: backend
    build: ./backend
    
    depends_on:
      - db
        
    volumes:
      - ./backend:/code/backend
    ports:
      - 8000:8000 
    command:   >
      sh -c "
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file: ./backend/.env

  redis:
    image: 'bitnami/redis:7.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
    - ./redis/path/to/certs:/opt/bitnami/redis/certs
    - ./reids/path/to/redis-persistence:/bitnami/redis/data
  
    
    
    
  
      



# version: '3'

# services:
#   db1:
#     image: mysql
#     container_name: db1
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: mypassword
#       MYSQL_DATABASE: mydatabase
#     networks:
#       my-network:
#         ipv4_address: 172.20.0.2

#   db2:
#     image: mysql
#     container_name: db2
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: mypassword
#       MYSQL_DATABASE: mydatabase
#     networks:
#       my-network:
#         ipv4_address: 172.20.0.3

# networks:
#   my-network:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.20.0.0/16