# Generated by Django 4.1.7 on 2023-03-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_baseuser_gender'),
        ('PersonalManagement', '0002_rename_hospitaldepartments_hospitaldepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDepartment',
            fields=[
                ('do_de_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalManagement.hospitaldepartment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
            ],
        ),
    ]
