# Generated by Django 4.1.7 on 2023-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalManagement', '0007_hospitaldepartment_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
