# Generated by Django 4.1.7 on 2023-03-30 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalManagement', '0008_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordepartment',
            name='do_de_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospitaldepartment',
            name='de_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
    ]
