# Generated by Django 4.1.7 on 2023-04-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalManagement', '0009_alter_doctordepartment_do_de_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.IntegerField(choices=[(1, 'DoctorNotarizedImage'), (2, 'Avatar')], max_length=60, null=True),
        ),
    ]
