# Generated by Django 4.1.7 on 2023-04-03 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PersonalManagement', '0010_alter_image_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('adress_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('adress_type', models.IntegerField(choices=[(1, 'CurrentAddress')], max_length=60, null=True)),
                ('base_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
