# Generated by Django 4.1.7 on 2023-04-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalManagement', '0012_rename_adress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
