# Generated by Django 4.1.7 on 2023-04-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalManagement', '0015_address_date_address_is_receive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_receive',
        ),
    ]
