# Generated by Django 4.1.7 on 2023-04-08 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PersonalManagement', '0016_remove_address_is_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='base_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to=settings.AUTH_USER_MODEL),
        ),
    ]
