# Generated by Django 4.1.7 on 2023-04-14 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalManagement', '0018_rename_image_imageuser_alter_imageuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDepartment',
            fields=[
                ('image_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('url', models.TextField(null=True)),
                ('image_type', models.IntegerField(choices=[(1, 'DoctorNotarizedImage'), (2, 'Avatar')], max_length=60, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='PersonalManagement.hospitaldepartment')),
            ],
            options={
                'db_table': 'ImageDepartment',
            },
        ),
    ]
