# Generated by Django 4.1.7 on 2023-04-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalManagement', '0019_imagedepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedepartment',
            name='image_type',
            field=models.IntegerField(choices=[(1, 'DoctorNotarizedImage'), (2, 'Avatar'), (3, 'DepartmentImage')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='imageuser',
            name='image_type',
            field=models.IntegerField(choices=[(1, 'DoctorNotarizedImage'), (2, 'Avatar'), (3, 'DepartmentImage')], max_length=60, null=True),
        ),
    ]
