# Generated by Django 4.1.7 on 2023-04-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0023_doctor_is_receive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectDoctor',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('doctor_channel', models.TextField()),
                ('patient_channel', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
    ]
