# Generated by Django 4.1.7 on 2023-04-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_doctor_is_receive'),
        ('Booking', '0002_alter_connectdoctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectdoctor',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.patient'),
        ),
        migrations.AlterField(
            model_name='connectdoctor',
            name='patient_channel',
            field=models.TextField(null=True),
        ),
    ]
