# Generated by Django 4.1.7 on 2023-05-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_connectdoctor_is_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectdoctor',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
