# Generated by Django 4.1.7 on 2023-05-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_doctor_diagnostic_fee_doctor_diagnostic_fee_gte_0'),
        ('Booking', '0006_connectdoctor_unique_conversation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connectdoctor',
            name='unique_conversation',
        ),
        migrations.AlterField(
            model_name='connectdoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor', unique=True),
        ),
        migrations.AlterField(
            model_name='connectdoctor',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.patient', unique=True),
        ),
    ]
