# Generated by Django 4.1.7 on 2023-03-01 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('base_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('base_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
    ]
