# Generated by Django 4.1.7 on 2023-03-01 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('base_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
