# Generated by Django 4.1.7 on 2023-03-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'Doctor'), (1, 'Patient'), (2, 'Admin')], null=True),
        ),
    ]
