# Generated by Django 4.1.7 on 2023-03-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='base_user_id',
            new_name='base_user',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='base_user_id',
            new_name='base_user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='base_user_id',
            new_name='base_user',
        ),
    ]
