# Generated by Django 4.1.7 on 2023-03-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_admin_base_user_alter_doctor_base_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.BooleanField(choices=[(2.0, 'Other'), (0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
