# Generated by Django 4.0 on 2023-03-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_baseuser_gender_alter_baseuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Male'), (1, 'Female'), (2.0, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
