# Generated by Django 4.1.7 on 2023-03-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_baseuser_is_hash_alter_baseuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='current_job',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='notarized_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Male'), (1, 'Female'), (2.0, 'Other')], null=True),
        ),
    ]
