# Generated by Django 4.1.7 on 2023-03-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_baseuser_birth_day_doctor_current_job_doctor_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
