# Generated by Django 4.1.7 on 2023-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_doctor_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.BooleanField(choices=[(2.0, 'Other'), (0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
