# Generated by Django 4.1.7 on 2023-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_remove_doctor_is_approved_alter_baseuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Male'), (2, 'Other'), (1, 'Female')], null=True),
        ),
    ]
