# Generated by Django 4.1.7 on 2023-03-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_baseuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_hash',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.BooleanField(choices=[(2, 'Other'), (1, 'Female'), (0, 'Male')], null=True),
        ),
    ]
