# Generated by Django 4.1.7 on 2023-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_remove_doctor_notarized_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='expreience',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='current_job',
            field=models.TextField(default=''),
        ),
    ]
