# Generated by Django 4.1.7 on 2023-04-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_doctor_expreience_alter_doctor_current_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='avatar',
        ),
    ]
