# Generated by Django 4.1.7 on 2023-04-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_remove_baseuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='address',
        ),
    ]
