# Generated by Django 4.1.7 on 2023-04-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_remove_baseuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_receive',
            field=models.BooleanField(default=False),
        ),
    ]
