# Generated by Django 4.1.7 on 2023-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_doctor_is_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='diagnostic_fee',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(check=models.Q(('diagnostic_fee__gte', 0)), name='diagnostic_fee_gte_0'),
        ),
    ]
